import { i18n } from "@/i18n.config";
import Providers from "@/lib/providers";
import type { TLocale } from "@/types/shared";
import { getLocale } from "@/utils/locales";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import { Monitoring } from "react-scan/monitoring/next";
import "../../../styles/globals.css";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

type Params = Promise<{ lang: TLocale }>;

export default async function RootLayout({
	children,
	params,
}: {
	children: ReactNode;
	params: Params;
}) {
	const param = await params;
	const lang = param.lang;
	const messages = await getLocale(lang);

	return (
		<html lang={lang} suppressHydrationWarning={true}>
			<body className={`${inter.className}} antialiased`}>
				{" "}
				<Monitoring
					apiKey="Io0GOtA29AqNStTqh3KuvxFi4BTqFECL"
					url="https://monitoring.react-scan.com/api/v1/ingest"
					commit={process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA}
					branch={process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF}
				/>
				<NextTopLoader
					color="#2299DD"
					initialPosition={0.08}
					crawlSpeed={200}
					height={3}
					crawl={true}
					showSpinner={true}
					easing="ease"
					speed={200}
					shadow="0 0 10px #2299DD,0 0 5px #2299DD"
				/>
				<Providers lang={lang} messages={messages}>
					{children}
				</Providers>
			</body>
		</html>
	);
}
