import {
	ArrowLeftRight,
	BadgeDollarSign,
	BriefcaseBusiness,
	BringToFront,
	ChartPie,
	Contact,
	DollarSign,
	FilePlus2,
	Gift,
	IdCard,
	Import,
	LayoutList,
	MessageSquareShare,
	Package,
	PackageSearch,
	ReplaceAll,
	SquareActivity,
	Store,
	Target,
	Ticket,
	Users,
	UsersRound,
} from "lucide-react";

export const Main = {
	base: [
		{
			id: "products",
			title: "Products",
			url: "/products",
			icon: PackageSearch,
			isActive: true,
			items: [
				{
					id: "categories",
					title: "Categories",
					url: "/products/categories",
					icon: LayoutList,
					shortcut: ["G", "N"],
				},
				{
					id: "import",
					title: "Import",
					url: "/products/import",
					icon: Import,
					shortcut: ["G", "N"],
				},
				{
					id: "orders",
					title: "Orders",
					url: "/products/orders",
					icon: BringToFront,
					shortcut: ["G", "N"],
				},
				{
					id: "inventory",
					title: "Inventory",
					url: "/products/inventory",
					icon: Package,
					shortcut: ["G", "N"],
				},
				{
					id: "transfer",
					title: "Transfer",
					url: "/products/transfer",
					icon: ArrowLeftRight,
					shortcut: ["G", "N"],
				},
			],
		},
		{
			id: "sales",
			title: "Sales",
			url: "/sales",
			icon: BadgeDollarSign,
			isActive: false,
			items: [
				{
					id: "new_sales",
					title: "New Sales",
					url: "/sales/new-sales",
					icon: FilePlus2,
					shortcut: ["G", "N"],
				},
				{
					id: "all_sales",
					title: "All Sales",
					url: "/sales/all-sales",
					icon: ReplaceAll,
					shortcut: ["G", "N"],
				},
			],
		},
		{
			id: "customers",
			title: "Customers",
			url: "/customers",
			icon: Users,
			isActive: false,
			items: [
				{
					id: "all_customers",
					title: "All Customers",
					url: "#",
					icon: UsersRound,
					shortcut: ["G", "N"],
				},
				{
					id: "customers_group",
					title: "Customers Group",
					url: "#",
					icon: Contact,
					shortcut: ["G", "N"],
				},
				{
					id: "customers_debt",
					title: "Customers Debt",
					url: "#",
					icon: IdCard,
					shortcut: ["G", "N"],
				},
			],
		},
		{
			id: "marketing",
			title: "Marketing",
			url: "/marketing",
			icon: SquareActivity,
			isActive: false,
			items: [
				{
					id: "promotions",
					title: "Promotions",
					url: "#",
					icon: Target,
					shortcut: ["G", "N"],
				},
				{
					id: "promo_codes",
					title: "Promo Codes",
					url: "#",
					icon: Ticket,
					shortcut: ["G", "N"],
				},
				{
					id: "send_sms",
					title: "Send SMS",
					url: "#",
					icon: MessageSquareShare,
					shortcut: ["G", "N"],
				},
				{
					id: "gift_cards",
					title: "Gift Cards",
					url: "#",
					icon: Gift,
					shortcut: ["G", "N"],
				},
			],
		},
		{
			id: "reports",
			title: "Reports",
			url: "/reports",
			icon: ChartPie,
			isActive: false,
			items: [
				{
					id: "shop",
					title: "Shop",
					url: "#",
					icon: Store,
					shortcut: ["G", "N"],
				},
				{
					id: "products",
					title: "Products",
					url: "#",
					icon: PackageSearch,
					shortcut: ["G", "N"],
				},
				{
					id: "vendors",
					title: "Vendors",
					url: "#",
					icon: Users,
					shortcut: ["G", "N"],
				},
				{
					id: "customers",
					title: "Customers",
					url: "#",
					icon: UsersRound,
					shortcut: ["G", "N"],
				},
				{
					id: "finances",
					title: "Finances",
					url: "#",
					icon: DollarSign,
					shortcut: ["G", "N"],
				},
			],
		},
	],
	management: [
		{
			id: "management",
			title: "Management",
			url: "/management",
			icon: BriefcaseBusiness,
			isActive: false,
			items: [
				{
					id: "workers",
					title: "Workers",
					url: "/management/workers",
					icon: Users,
					shortcut: ["G", "W"],
				},
				{
					id: "roles",
					title: "Roles",
					url: "/management/roles",
					icon: Import,
					shortcut: ["G", "R"],
				},
			],
		},
	],
};
